# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-12 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
