# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180412_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
